imagePullPolicy: IfNotPresent
backendreplicacount: 1
backend:
  internalPort: 8080
  externalPort: 8081
  serviceType: NodePort
frontend:
  internalPort: 8080
  externalPort: 8080  
  nodePort: 30000
  serviceType: NodePort
