apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-one
spec:
  replicas: {{ .Values.backendreplicacount}}
  selector:
    matchLabels:
      app: backend-one
  template:
    metadata:
      labels:
        app: backend-one
    spec:
      containers:
      - name: worker
        image: backendimage:1.0.2
        imagePullPolicy: {{ .Values.imagePullPolicy }}
      - name: worker2
        image: alpine
        command: [ "sh", "-c", "while true; do echo I am working; sleep 5; done" ]
        imagePullPolicy: {{ .Values.imagePullPolicy }}
