apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-one
  template:
    metadata:
      labels:
        app: backend-one
    spec:
      containers:
      - name: worker
        image: alpine
        command: ["sh", "-c", "while true; do echo I am working; sleep 5; done"]
