apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: {{ .Values.backend.serviceType }}
  selector:
    app: backend-deployment
  ports:
    - port: {{ .Values.backend.externalPort}}
      targetPort: {{ .Values.backend.internalPort}}
