apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-three
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-three
  template:
    metadata:
      labels:
        app: ui-three
    spec:
      containers:
      - name: ui
        image: nginx
        imagePullPolicy: {{ .Values.imagePullPolicy }}
