apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  type: {{ .Values.frontend.serviceType }}
  selector:
    app: ui-deployment
  ports:
    - port: {{ .Values.frontend.externalPort}}
      targetPort: {{ .Values.frontend.internalPort}}
      nodePort: {{ .Values.frontend.nodePort}}
