apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-two
  template:
    metadata:
      labels:
        app: api-two
    spec:
      containers:
      - name: api
        image: nginx
